// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrongTowing.Infrastructure.Data;

#nullable disable

namespace StrongTowing.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260414154601_PricingModelAccountServiceRates")]
    partial class PricingModelAccountServiceRates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasChangedPassword")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailableForDispatch")
                        .HasColumnType("bit");

                    b.Property<double?>("LastKnownLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("LastKnownLongitude")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastLocationUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.AuthOtpRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail", "Purpose", "Used");

                    b.ToTable("AuthOtpRecords");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.CashCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("JobId");

                    b.HasIndex("PaymentId");

                    b.ToTable("CashCollections");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.DriverPayroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CashCollections")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommissionPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalizedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrossEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaidBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PayPeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PayPeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalJobMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalJobRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalJobs")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverId", "PayPeriodStart", "PayPeriodEnd")
                        .IsUnique();

                    b.ToTable("DriverPayrolls");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.InsuranceAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BillingEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BillingPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HookupFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTaxExemptByDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("RateAB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RateBC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RateCA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServiceChargePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("State")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("TaxPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InsuranceAccounts");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.InsuranceAccountServiceRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HookFeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HookFeeEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("InsuranceAccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerMile")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServicePricingProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ServicePricingProfileId");

                    b.HasIndex("InsuranceAccountId", "ServicePricingProfileId")
                        .IsUnique();

                    b.ToTable("InsuranceAccountServiceRates");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingPaymentMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CallType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CancellationFeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelledBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ClientCoveredAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ClientPortionPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("CommissionVisibleToDriver")
                        .HasColumnType("bit");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drivable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DriverCashCollectedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DriverId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ETA")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HaveKeys")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeBillingNotesOnReceipt")
                        .HasColumnType("bit");

                    b.Property<decimal?>("InsuranceCoveredAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("InsurancePortionBilled")
                        .HasColumnType("bit");

                    b.Property<string>("InvoiceChargesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Odometer")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaidBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PayrollDeductionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PayrollDeductionRecorded")
                        .HasColumnType("bit");

                    b.Property<string>("PickupLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("ScheduledTime")
                        .HasColumnType("time");

                    b.Property<string>("ServiceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StatusUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusUpdatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TruckId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("StatusUpdatedById");

                    b.HasIndex("VehicleId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.JobPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobPhotos");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("AuthorizationExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("AuthorizedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CancellationFeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CancellationFeePolicySnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaptureStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CapturedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CardBrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardLast4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CashCollectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CashCollectedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FraudReasons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FraudReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FraudReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FraudScore")
                        .HasColumnType("int");

                    b.Property<string>("FraudStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsCancellationFeePayment")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPreAuthorization")
                        .HasColumnType("bit");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentLinkId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RefundReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StripeChargeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePaymentLinkId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePaymentLinkUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("PaymentStatus", "FraudStatus");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.PendingDriverSignup", b =>
                {
                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ProtectedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NormalizedEmail");

                    b.ToTable("PendingDriverSignups");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Token");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.ServicePricingProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HookFeeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HookFeeEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PricePerMile")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ServicePricingProfiles");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowManualTotalOverride")
                        .HasColumnType("bit");

                    b.Property<decimal>("CancelFeeAfterArrivalPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("CancelFeeAfterDispatchPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("CancelFeeBeforeDispatchPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DefaultPricingHookupFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DefaultPricingServiceChargePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DefaultPricingTaxPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("DriverCommissionPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DuplicateRequestWindowMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("EmailClientDriverAssigned")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailClientFraudUnderReview")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailClientJobCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailClientJobCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailClientJobCreated")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailClientPaymentFailed")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailClientPaymentLinkCreated")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailClientPaymentSucceeded")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailClientStatusLoaded")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailClientStatusOnRoute")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailClientStatusOnScene")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailDriverJobAssigned")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailDriverJobCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailDriverPayrollPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("FraudReviewScoreThreshold")
                        .HasColumnType("int");

                    b.Property<bool>("ManualOverrideRequiresReason")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxDiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<double?>("OfficeLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("OfficeLongitude")
                        .HasColumnType("float");

                    b.Property<string>("PayPeriodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostmarkDefaultFromEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostmarkMessageStream")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostmarkServerToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PreAuthorizationEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("PreAuthorizationMaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreAuthorizationMinAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricingFreeMiles")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricingMismatchTolerance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PricingRoundingMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SmsClientDriverAssigned")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsClientFraudUnderReview")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsClientJobCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsClientJobCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsClientJobCreated")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsClientPaymentFailed")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsClientPaymentLinkCreated")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsClientPaymentSucceeded")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsClientStatusLoaded")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsClientStatusOnRoute")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsClientStatusOnScene")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsDriverJobAssigned")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsDriverJobCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsDriverPayrollPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("SmsTwilioAccountSid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmsTwilioAuthToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmsTwilioFromNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmsTwilioMessagingServiceSid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StripeEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("StripeLivePublicKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeLiveSecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeLiveWebhookSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePublicKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeTestPublicKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeTestSecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeTestWebhookSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeWebhookSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.UserFcmToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(4096)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserFcmTokens");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.VehicleCatalogMake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NhtsaMakeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NhtsaMakeId")
                        .IsUnique();

                    b.ToTable("VehicleCatalogMakes");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.VehicleCatalogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NhtsaModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MakeId", "NhtsaModelId")
                        .IsUnique();

                    b.ToTable("VehicleCatalogModels");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.VehicleCatalogSyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastSyncCompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("LastSyncStartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MakesCount")
                        .HasColumnType("int");

                    b.Property<int>("MakesProcessed")
                        .HasColumnType("int");

                    b.Property<int>("ModelsAddedSoFar")
                        .HasColumnType("int");

                    b.Property<int>("ModelsCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalMakes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VehicleCatalogSyncStates");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StrongTowing.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StrongTowing.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StrongTowing.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StrongTowing.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.CashCollection", b =>
                {
                    b.HasOne("StrongTowing.Core.Entities.ApplicationUser", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StrongTowing.Core.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StrongTowing.Core.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Job");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.DriverPayroll", b =>
                {
                    b.HasOne("StrongTowing.Core.Entities.ApplicationUser", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.InsuranceAccountServiceRate", b =>
                {
                    b.HasOne("StrongTowing.Core.Entities.InsuranceAccount", "InsuranceAccount")
                        .WithMany()
                        .HasForeignKey("InsuranceAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StrongTowing.Core.Entities.ServicePricingProfile", "ServicePricingProfile")
                        .WithMany()
                        .HasForeignKey("ServicePricingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsuranceAccount");

                    b.Navigation("ServicePricingProfile");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.Job", b =>
                {
                    b.HasOne("StrongTowing.Core.Entities.ApplicationUser", "Driver")
                        .WithMany("AssignedJobs")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StrongTowing.Core.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StrongTowing.Core.Entities.ApplicationUser", "StatusUpdatedBy")
                        .WithMany()
                        .HasForeignKey("StatusUpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StrongTowing.Core.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Payment");

                    b.Navigation("StatusUpdatedBy");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.JobPhoto", b =>
                {
                    b.HasOne("StrongTowing.Core.Entities.Job", "Job")
                        .WithMany("Photos")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.Payment", b =>
                {
                    b.HasOne("StrongTowing.Core.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("StrongTowing.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.UserFcmToken", b =>
                {
                    b.HasOne("StrongTowing.Core.Entities.ApplicationUser", "User")
                        .WithMany("FcmTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("StrongTowing.Core.Entities.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.VehicleCatalogModel", b =>
                {
                    b.HasOne("StrongTowing.Core.Entities.VehicleCatalogMake", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("AssignedJobs");

                    b.Navigation("FcmTokens");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.Job", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("StrongTowing.Core.Entities.VehicleCatalogMake", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
